// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vehicles.Api.Data;

#nullable disable

namespace Vehicles.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vehicles.Api.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BodyType = "Hatchback",
                            Brand = "Volkswagen",
                            Color = "White",
                            Engine = "1.0 TSI",
                            IsNew = true,
                            Model = "Polo",
                            Price = 18500m,
                            Year = 2026
                        },
                        new
                        {
                            Id = 2,
                            BodyType = "Hatchback",
                            Brand = "Volkswagen",
                            Color = "Black",
                            Engine = "1.5 TSI",
                            IsNew = true,
                            Model = "Golf",
                            Price = 24500m,
                            Year = 2026
                        },
                        new
                        {
                            Id = 3,
                            BodyType = "SUV",
                            Brand = "Volkswagen",
                            Color = "Grey",
                            Engine = "2.0 TDI",
                            IsNew = true,
                            Model = "Tiguan",
                            Price = 34500m,
                            Year = 2026
                        },
                        new
                        {
                            Id = 4,
                            BodyType = "Sedan",
                            Brand = "Volkswagen",
                            Color = "Blue",
                            Engine = "2.0 TDI",
                            IsNew = true,
                            Model = "Passat",
                            Price = 33500m,
                            Year = 2026
                        },
                        new
                        {
                            Id = 5,
                            BodyType = "Hatchback",
                            Brand = "Audi",
                            Color = "Blue",
                            Engine = "1.5 TFSI",
                            IsNew = true,
                            Model = "A3",
                            Price = 28000m,
                            Year = 2026
                        },
                        new
                        {
                            Id = 6,
                            BodyType = "Sedan",
                            Brand = "Audi",
                            Color = "Black",
                            Engine = "2.0 TDI",
                            IsNew = true,
                            Model = "A4",
                            Price = 42000m,
                            Year = 2026
                        },
                        new
                        {
                            Id = 7,
                            BodyType = "Sedan",
                            Brand = "Audi",
                            Color = "Grey",
                            Engine = "2.0 TDI",
                            IsNew = true,
                            Model = "A6",
                            Price = 55000m,
                            Year = 2026
                        },
                        new
                        {
                            Id = 8,
                            BodyType = "SUV",
                            Brand = "Audi",
                            Color = "White",
                            Engine = "1.5 TFSI",
                            IsNew = true,
                            Model = "Q3",
                            Price = 38000m,
                            Year = 2026
                        },
                        new
                        {
                            Id = 9,
                            BodyType = "SUV",
                            Brand = "Audi",
                            Color = "White",
                            Engine = "2.0 TFSI",
                            IsNew = true,
                            Model = "Q5",
                            Price = 52000m,
                            Year = 2026
                        },
                        new
                        {
                            Id = 10,
                            BodyType = "Hatchback",
                            Brand = "Seat",
                            Color = "Red",
                            Engine = "1.0 MPI",
                            IsNew = true,
                            Model = "Ibiza",
                            Price = 16500m,
                            Year = 2026
                        },
                        new
                        {
                            Id = 11,
                            BodyType = "Hatchback",
                            Brand = "Seat",
                            Color = "Silver",
                            Engine = "1.5 TSI",
                            IsNew = true,
                            Model = "Leon",
                            Price = 23000m,
                            Year = 2026
                        },
                        new
                        {
                            Id = 12,
                            BodyType = "SUV",
                            Brand = "Seat",
                            Color = "Orange",
                            Engine = "1.0 TSI",
                            IsNew = true,
                            Model = "Arona",
                            Price = 21000m,
                            Year = 2026
                        },
                        new
                        {
                            Id = 13,
                            BodyType = "Sedan",
                            Brand = "Skoda",
                            Color = "Blue",
                            Engine = "2.0 TDI",
                            IsNew = true,
                            Model = "Octavia",
                            Price = 27500m,
                            Year = 2026
                        },
                        new
                        {
                            Id = 14,
                            BodyType = "Hatchback",
                            Brand = "Skoda",
                            Color = "White",
                            Engine = "1.0 TSI",
                            IsNew = true,
                            Model = "Fabia",
                            Price = 17500m,
                            Year = 2026
                        },
                        new
                        {
                            Id = 15,
                            BodyType = "SUV",
                            Brand = "Skoda",
                            Color = "Black",
                            Engine = "2.0 TDI",
                            IsNew = true,
                            Model = "Kodiaq",
                            Price = 39500m,
                            Year = 2026
                        },
                        new
                        {
                            Id = 16,
                            BodyType = "Hatchback",
                            Brand = "Volkswagen",
                            Color = "Blue",
                            Engine = "1.6 TDI",
                            IsNew = false,
                            Model = "Golf",
                            Price = 8500m,
                            Year = 2015
                        },
                        new
                        {
                            Id = 17,
                            BodyType = "Wagon",
                            Brand = "Skoda",
                            Color = "Silver",
                            Engine = "2.0 TDI",
                            IsNew = false,
                            Model = "Octavia",
                            Price = 9800m,
                            Year = 2017
                        },
                        new
                        {
                            Id = 18,
                            BodyType = "Sedan",
                            Brand = "Volkswagen",
                            Color = "Black",
                            Engine = "2.0 TDI",
                            IsNew = false,
                            Model = "Passat",
                            Price = 10500m,
                            Year = 2016
                        },
                        new
                        {
                            Id = 19,
                            BodyType = "Sedan",
                            Brand = "Audi",
                            Color = "Grey",
                            Engine = "2.0 TDI",
                            IsNew = false,
                            Model = "A4",
                            Price = 9200m,
                            Year = 2014
                        },
                        new
                        {
                            Id = 20,
                            BodyType = "Hatchback",
                            Brand = "Seat",
                            Color = "Red",
                            Engine = "1.6 TDI",
                            IsNew = false,
                            Model = "Leon",
                            Price = 6500m,
                            Year = 2013
                        },
                        new
                        {
                            Id = 21,
                            BodyType = "Hatchback",
                            Brand = "Volkswagen",
                            Color = "White",
                            Engine = "1.0 TSI",
                            IsNew = false,
                            Model = "Polo",
                            Price = 9700m,
                            Year = 2018
                        },
                        new
                        {
                            Id = 22,
                            BodyType = "Hatchback",
                            Brand = "Skoda",
                            Color = "Blue",
                            Engine = "1.2 TSI",
                            IsNew = false,
                            Model = "Fabia",
                            Price = 6200m,
                            Year = 2016
                        },
                        new
                        {
                            Id = 23,
                            BodyType = "SUV",
                            Brand = "Audi",
                            Color = "Black",
                            Engine = "2.0 TDI",
                            IsNew = false,
                            Model = "Q3",
                            Price = 13500m,
                            Year = 2015
                        },
                        new
                        {
                            Id = 24,
                            BodyType = "Hatchback",
                            Brand = "Seat",
                            Color = "Yellow",
                            Engine = "1.0 MPI",
                            IsNew = false,
                            Model = "Ibiza",
                            Price = 8900m,
                            Year = 2019
                        },
                        new
                        {
                            Id = 25,
                            BodyType = "SUV",
                            Brand = "Volkswagen",
                            Color = "Grey",
                            Engine = "2.0 TDI",
                            IsNew = false,
                            Model = "Tiguan",
                            Price = 15500m,
                            Year = 2017
                        },
                        new
                        {
                            Id = 26,
                            BodyType = "Hatchback",
                            Brand = "Audi",
                            Color = "Blue",
                            Engine = "1.4 TFSI",
                            IsNew = false,
                            Model = "A3",
                            Price = 11500m,
                            Year = 2016
                        },
                        new
                        {
                            Id = 27,
                            BodyType = "Sedan",
                            Brand = "Skoda",
                            Color = "Black",
                            Engine = "2.0 TDI",
                            IsNew = false,
                            Model = "Superb",
                            Price = 12500m,
                            Year = 2015
                        },
                        new
                        {
                            Id = 28,
                            BodyType = "SUV",
                            Brand = "Seat",
                            Color = "Orange",
                            Engine = "1.0 TSI",
                            IsNew = false,
                            Model = "Arona",
                            Price = 14500m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 29,
                            BodyType = "Wagon",
                            Brand = "Volkswagen",
                            Color = "White",
                            Engine = "1.6 TDI",
                            IsNew = false,
                            Model = "Passat",
                            Price = 7200m,
                            Year = 2013
                        },
                        new
                        {
                            Id = 30,
                            BodyType = "Sedan",
                            Brand = "Audi",
                            Color = "Silver",
                            Engine = "2.0 TDI",
                            IsNew = false,
                            Model = "A6",
                            Price = 8900m,
                            Year = 2012
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
